/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Data.LinkedList;

public class LinkedList {

    Node head; //this is the head of the list


    public void insert(Object newData) {
        Node newNode = new Node(newData); //creating the new Node
        newNode.next = head; //assigning the current head to the next node
        head = newNode; //change head to be the newNode added
    }

    public boolean includes(Object data){

        Node current = head;
        while(current != null){
            if(current.data == data){
                return true;
            }
            current = current.next;
        }

    return false;
    }
}
